[Variables]

;==========================
; Dashboard
;==========================

DashboardWidth=470
DashboardPadding=24
CardWidth=422
CardHeight=95
CardRadius=18

;==========================
; Colours
;==========================

Background=24,24,27,235
CardBackground=40,42,46,215

PrimaryText=255,255,255
SecondaryText=185,185,190

Accent=72,0,255,200

;==========================
; Fonts
;==========================

TitleFont=Bahnschrift Light
BodyFont=Segoe UI
IconFont=Segoe Fluent Icons

GreetingSize=24
DateSize=11
CardTitleSize=15
CardBodySize=11